spring:
  application:
    name: gateway
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 1MB
      location: /
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: CLIENT
          uri: lb://CLIENT
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
        - id: spring-cloud-client-demo3
          uri: lb://spring-cloud-client-demo
          predicates:
            - Path=/websocket/**
          filters:
            - StripPrefix=1
        - id: spring-cloud-client-demo4
          uri: lb:ws://spring-cloud-client-demo
          predicates:
            - Path=/websocket/**
server:
  port: 8888
eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug