spring:
  profiles:
    active: test

version: 1.0
# 是否启用 Dataway 功能（必选：默认false）
HASOR_DATAQL_DATAWAY: true
# 是否开启 Dataway 后台管理界面（必选：默认false）
HASOR_DATAQL_DATAWAY_ADMIN: true
# dataway  API工作路径（可选，默认：/api/）
HASOR_DATAQL_DATAWAY_API_URL: /api/
# dataway-ui 的工作路径（可选，默认：/interface-ui/）
HASOR_DATAQL_DATAWAY_UI_URL: /interface-ui/
# SQL执行器方言设置（可选，建议设置）
HASOR_DATAQL_FX_PAGE_DIALECT: mysql

upload:
  file-path: /Users/yibaiyi/tool/upload/
  api-server-addr: 'https://wechat.samic.com.cn/zuul-platform'