spring:
  application:
    name: client
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      auto-commit: true
      minimum-idle: 5
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
      pool-name: DatebookHikariCP
      maximum-pool-size: 30
      jdbc-url: jdbc:mysql://127.0.0.1:3306/springcloud?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

server:
  port: 8661

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.ljryh.client.entity
  configuration:
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl